version: '3'
services:
  app:
    build: .
    ports:
      - "10.0.0.204:5000:5000"
    volumes:
      - ./backend/uploads:/app/backend/uploads
      - ./backend/outputs:/app/backend/outputs
      - ./frontend:/app/frontend
